# Generated by Django 5.0.2 on 2024-02-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(choices=[('black', 'черный'), ('white', 'белый'), ('red', 'красный'), ('green', 'зеленый'), ('yellow', 'желтый'), ('blue', 'синий')], max_length=20, verbose_name='Цвет')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('image', models.ImageField(blank='True', null='True', upload_to='cars/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('econom', 'эконом'), ('comfort', 'комфорт'), ('comfort+', 'комфорт+'), ('business', 'бизнес'), ('luxe', 'люкс')], max_length=10, verbose_name='Класс авто')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='employers.carbrand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
