# Generated by Django 5.0.2 on 2024-02-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_department_position_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Статус машины'),
        ),
    ]
